#pragma once

#include <boost/json.cpp>
#include <string>
#include "enums/conf-3.enums.h"

class config3_data
{
    bool bool decodeConfig_;
    bool pictureTurn_;
    bool oneDReverse_;
    bool code69Enable_;
    bool EAN13Enable_;
    bool EAN13ParityBitOut_;
    bool EAN13ToISSN_;
    bool EAN13ToISBN_;
    bool EAN13ExtraOut_;
    bool EAN13Extra2Bits_;
    bool EAN13Extra5Bits_;
    bool EAN8Enable_;
    bool EAN8ParityBitOut_;
    bool EAN8ExtraOut_;
    bool EAN8Extra2Bits_;
    bool EAN8Extra5Bits_;
    bool UPCAEnable_;
    bool UPCAParityBitOut_;
    bool UPCAToEAN13_;
    bool UPCAExtraOut_;
    bool UPCAExtra2Bits_;
    bool UPCAExtra5Bits_;
    bool UPCE0Enable_;
    bool UPCE0ParityBitOut_;
    bool UPCE1ToEAN13_;
    bool UPCE1ExtraOut_;
    bool UPCE1Extra2Bits_;
    bool UPCE1Extra5Bits_;
    bool code128Enable_;
    unsigned int code128MessageMinLen_;
    unsigned int code128MessageMaxLen_;
    bool code39Enable_;
    bool code39ParityOut_;
    bool code39ParityProcess_;
    bool code39FullASCII_;
    bool code39Code32Mode_;
    bool code39Code32Lead_;
    bool code39Head_;
    bool code39Tail_;
    unsigned int code39MessageMinLen_;
    unsigned int code39MessageMaxLen_;
    bool code93Enable_;
    unsigned int code93MessageMinLen_;
    unsigned int code93MessageMaxLen_;
    bool codeBarEnable_;
    bool codeBarOutHead_Tail_;
    bool codeBarMod16Parity_;
    bool codeBarMod10Parity_;
    bool codeBarParityOutEnable_;
    unsigned int codeBarMessageMinLen_;
    unsigned int codeBarMessageMaxLen_;
    bool QREnable_;
    bool QRMode1Switch_;
    bool interleaved2of5Enable_;
    bool interleaved2of5ParityOut_;
    interleaved2of5ParityProcess interleaved2of5ParityProcess_;
    unsigned int interleaved2of5MessageMinLen_;
    unsigned int interleaved2of5MessageMaxLen_;
    bool industrial25Enable_;
    bool industrial25ParityOut_;
    industrial25ParityProcess industrial25ParityProcess_;
    unsigned int industrial25MessageMinLen_;
    unsigned int industrial25MessageMaxLen_;
    bool matrix2of5Enable_;
    bool matrix2of5ParityOut_;
    matrix2of5ParityProcess matrix2of5ParityProcess_;
    unsigned int matrix2of5MessageMinLen_;
    unsigned int matrix2of5MessageMaxLen_;
    bool code11Enable_;
    bool code11ParityProcess_;
    code11ParityProcess code11ParityProcess_;
    unsigned int code11MessageMinLen_;
    unsigned int code11MessageMaxLen_;
    bool MSIEnable_;
    bool MSIParityOut_;
    MSIParityProcess MSIParityProcess_;
    unsigned int MSIMessageMinLen_;
    unsigned int MSIMessageMaxLen_;
    bool GS1DatabarEnable_;
    bool GS1DatabarRss_14ParityBitsOut_;
    bool GS1DatabarAIBracket_;
    bool GS1DatabarLimitedEnable_;
    bool GS1DatabarLimitedRssParity_;
    bool GS1DatabarLimitedAIBracket_;
    bool GS1DatabarExpansionEnable_;
    bool GS1DatabarExpansionRssParity_;
    bool GS1DatabarExpansionAIBracket_;
    unsigned int GS1DatabarExpansionMessageMinLen_;
    unsigned int GS1DatabarExpansionMessageMaxLen_;
    bool DMEnable_;
    bool DMMultiCodeEnable_;
    bool PDF417Enable_;
    bool HanXinEnable_;
    bool MicroPDF417Enable_;
    bool MicroQREnable_;
    bool MaxiCodeEnable_;
    bool AztecEnable_;
    bool standard25Enable_;
    bool standard25ParityOut_;
    bool standard25ParityProcess_;
    unsigned int standard25MessageMinLen_;
    unsigned int standard25MessageMaxLen_;
    bool GS1CompositeEnable_;
    bool GMEnable_;
    bool GMDataExpansion_;
    bool GMAIBracketOut_;
    bool GMECIOut_;
    bool plesseyEnable_;
    bool plesseyOutParityBit_;
    bool plesseyParityProcess_;
    unsigned int plesseyMessageMinLen_;
    unsigned int plesseyMessageMaxLen_;
    bool chinaPost25Enable_;
    bool chinaPost25OutParityBit_;
    bool chinaPost25ParityProcess_;
    unsigned int chinaPost25MessageMinLen_;
    unsigned int chinaPost25MessageMaxLen_;
    bool code16KEnable_;
    bool code16KMessageMinLen_;
    bool code16KMessageMaxLen_;
    bool code49Enable_;
    unsigned int code49MessageMinLen_;
    unsigned int code49MessageMaxLen_;
    bool specSet1Enable_;
};